<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publisher extends \App\Entity\Publisher implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyUrl', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyEmail', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyTelephone', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'enabled'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyName', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyUrl', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyEmail', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'companyTelephone', '' . "\0" . 'App\\Entity\\Publisher' . "\0" . 'enabled'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publisher $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName(?string $firstName): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName(?string $lastName): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', []);

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName(?string $companyName): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', [$companyName]);

        return parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyUrl', []);

        return parent::getCompanyUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyUrl(?string $companyUrl): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyUrl', [$companyUrl]);

        return parent::setCompanyUrl($companyUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyEmail', []);

        return parent::getCompanyEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyEmail(?string $companyEmail): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyEmail', [$companyEmail]);

        return parent::setCompanyEmail($companyEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyTelephone', []);

        return parent::getCompanyTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyTelephone(?string $companyTelephone): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyTelephone', [$companyTelephone]);

        return parent::setCompanyTelephone($companyTelephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled(?string $enabled): \App\Entity\Publisher
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

}
