<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8YhKBM\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8YhKBM/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerM8YhKBM.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerM8YhKBM\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerM8YhKBM\App_KernelTestDebugContainer([
    'container.build_hash' => 'M8YhKBM',
    'container.build_id' => '28773946',
    'container.build_time' => 1595809477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8YhKBM');
