<?php

namespace ContainerM8YhKBM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebsiteControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\WebsiteController' shared autowired service.
     *
     * @return \App\Controller\WebsiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WebsiteController.php';

        $container->services['App\\Controller\\WebsiteController'] = $instance = new \App\Controller\WebsiteController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\WebsiteController', $container));

        return $instance;
    }
}
