<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYVfuqSf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYVfuqSf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYVfuqSf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYVfuqSf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYVfuqSf\App_KernelDevDebugContainer([
    'container.build_hash' => 'YVfuqSf',
    'container.build_id' => 'a5e78ba6',
    'container.build_time' => 1595809377,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYVfuqSf');
